version: '3'
services:
  aurora-mongo:
    image: mongo
    container_name: aurora-mongo
    volumes:
      - '.docker-volumes/mongo/data/db:/data/db'
      - '$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/'
    ports:
      - 27017:27017
    env_file:
      - .env
  aurora-redis:
    image: redis
    container_name: aurora-redis
    command: >
      --requirepass ${REDIS_DB_PASSWORD}
    ports:
      - 6379:6379
    env_file:
      - .env
  aurora-backend:
    depends_on:
      - aurora-mongo
      - aurora-redis
    build:
      context: .
      dockerfile: Dockerfile
    image: aurora-backend
    container_name: aurora-backend
    ports:
      - 7001:7001
    env_file:
      - .env
