version: '3'
services:
  aurora-mongo:
    image: mongo
    container_name: aurora-mongo
    volumes:
      - '.docker-volumes/mongo/data/db:/data/db'
      - '$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/'
    ports:
      - 27018:27017
    env_file:
      - .env
  aurora-redis:
    image: redis
    container_name: aurora-redis
    command: >
      --requirepass ${REDIS_DB_PASSWORD}
    ports:
      - 6378:6379
    env_file:
      - .env
  aurora-backend:
    image: registry.cn-hangzhou.aliyuncs.com/jason-aurora/aurora:0.0.2
    container_name: aurora-backend
    ports:
      - 7002:7001
    env_file:
      - .env
